; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32doit-devkit-v1]
platform = espressif32
board = esp32doit-devkit-v1
framework = espidf

monitor_speed = 115200

; Board profile says 4MB; ESP-IDF sdkconfig uses 2MB
board_build.flash_size = 2MB
board_upload.flash_size = 2MB

; USB serial settings
upload_port = /dev/ttyUSB1
monitor_port = /dev/ttyUSB1

; Set your WiFi password here (SSID is brxxxx in main.c)
; build_flags = -D WIFI_PASS=\"your_wifi_password\"
