#include "index_html.h"

const char index_html[] =
"<!DOCTYPE html>\n"
"<html lang=\"en\">\n"
"<head>\n"
"  <meta charset=\"UTF-8\" />\n"
"  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />\n"
"  <title>IMU 3D Viewer</title>\n"
"  <style>\n"
"    * { margin: 0; padding: 0; box-sizing: border-box; }\n"
"    body { overflow: hidden; background: #1a1a2e; font-family: system-ui, sans-serif; }\n"
"    #hud {\n"
"      position: fixed; top: 12px; left: 12px; z-index: 10;\n"
"      color: #eee; background: rgba(0,0,0,0.55); padding: 10px 14px;\n"
"      border-radius: 8px; font-size: 14px; line-height: 1.5;\n"
"    }\n"
"    #hud button {\n"
"      margin-top: 8px; padding: 6px 14px; cursor: pointer;\n"
"      border: none; border-radius: 6px; background: #4a9eff; color: #fff;\n"
"      font-size: 14px;\n"
"    }\n"
"    #hud button:hover { background: #3a8eef; }\n"
"    #ipRow { margin-top: 8px; display: flex; gap: 6px; align-items: center; }\n"
"    #ipRow input {\n"
"      width: 130px; padding: 4px 8px; border-radius: 4px; border: none;\n"
"      font-size: 13px;\n"
"    }\n"
"    .ok { color: #6f6; }\n"
"    .err { color: #f66; }\n"
"    #activity {\n"
"      margin-top: 6px; padding: 6px 10px; border-radius: 6px;\n"
"      font-weight: 600; letter-spacing: 0.02em;\n"
"    }\n"
"    #activity.still { background: rgba(255,255,255,0.08); color: #bbb; }\n"
"    #activity.walking { background: rgba(80,200,120,0.25); color: #8f8; }\n"
"    #vitals {\n"
"      position: fixed; top: 12px; right: 12px; z-index: 10;\n"
"      color: #eee; background: rgba(0,0,0,0.55); padding: 12px 16px;\n"
"      border-radius: 8px; font-size: 14px; line-height: 1.6; min-width: 148px;\n"
"    }\n"
"    #vitals h3 {\n"
"      margin: 0 0 8px; font-size: 12px; font-weight: 600;\n"
"      letter-spacing: 0.06em; text-transform: uppercase; color: #aaa;\n"
"    }\n"
"    #vitals .row {\n"
"      display: flex; justify-content: space-between; align-items: baseline;\n"
"      gap: 12px;\n"
"    }\n"
"    #vitals .label { color: #bbb; }\n"
"    #vitals .value { font-weight: 600; font-variant-numeric: tabular-nums; }\n"
"    #vitals .value.missing { color: #888; font-weight: 400; }\n"
"  </style>\n"
"</head>\n"
"<body>\n"
"  <div id=\"hud\">\n"
"    <div id=\"status\">Connecting…</div>\n"
"    <div id=\"fps\">FPS: —</div>\n"
"    <div id=\"activity\" class=\"still\">Still</div>\n"
"    <div id=\"ipRow\" hidden>\n"
"      <input id=\"espIp\" type=\"text\" placeholder=\"192.168.0.195\" />\n"
"      <button id=\"connectBtn\" type=\"button\">Connect</button>\n"
"    </div>\n"
"    <button id=\"resetBtn\" type=\"button\">Calibrate / zero</button>\n"
"  </div>\n"
"  <div id=\"vitals\">\n"
"    <h3>Vitals</h3>\n"
"    <div class=\"row\"><span class=\"label\">Temp</span><span class=\"value missing\" id=\"vTemp\">--</span></div>\n"
"    <div class=\"row\"><span class=\"label\">Heart rate</span><span class=\"value missing\" id=\"vHr\">--</span></div>\n"
"    <div class=\"row\"><span class=\"label\">SpO2</span><span class=\"value missing\" id=\"vSpo2\">--</span></div>\n"
"    <div class=\"row\"><span class=\"label\">MQ-135</span><span class=\"value missing\" id=\"vMq135\">--</span></div>\n"
"    <div class=\"row\"><span class=\"label\">MQ-136</span><span class=\"value missing\" id=\"vMq136\">--</span></div>\n"
"    <div class=\"row\"><span class=\"label\">MQ-4</span><span class=\"value missing\" id=\"vMq4\">--</span></div>\n"
"    <div class=\"row\"><span class=\"label\">MQ-7</span><span class=\"value missing\" id=\"vMq7\">--</span></div>\n"
"  </div>\n"
"  <script type=\"importmap\">\n"
"  {\n"
"    \"imports\": {\n"
"      \"three\": \"https://cdn.jsdelivr.net/npm/three@0.160.0/build/three.module.js\",\n"
"      \"three/addons/\": \"https://cdn.jsdelivr.net/npm/three@0.160.0/examples/jsm/\"\n"
"    }\n"
"  }\n"
"  </script>\n"
"  <script type=\"module\">\n"
"    import * as THREE from 'three';\n"
"    import { OrbitControls } from 'three/addons/controls/OrbitControls.js';\n"
"    import { GLTFLoader } from 'three/addons/loaders/GLTFLoader.js';\n"
"\n"
"    const statusEl = document.getElementById('status');\n"
"    const fpsEl = document.getElementById('fps');\n"
"    const activityEl = document.getElementById('activity');\n"
"    const resetBtn = document.getElementById('resetBtn');\n"
"    const ipRow = document.getElementById('ipRow');\n"
"    const espIpInput = document.getElementById('espIp');\n"
"    const connectBtn = document.getElementById('connectBtn');\n"
"    const vTempEl = document.getElementById('vTemp');\n"
"    const vHrEl = document.getElementById('vHr');\n"
"    const vSpo2El = document.getElementById('vSpo2');\n"
"    const vMq135El = document.getElementById('vMq135');\n"
"    const vMq136El = document.getElementById('vMq136');\n"
"    const vMq4El = document.getElementById('vMq4');\n"
"    const vMq7El = document.getElementById('vMq7');\n"
"    const servedFromEsp = location.protocol === 'http:' || location.protocol === 'https:';\n"
"\n"
"    /* Poly Pizza hardhat: https://poly.pizza/m/cyjbHPC6QAM (CC Attribution, Poly by Google) */\n"
"    const HELMET_GLB_LOCAL = 'models/helmet.glb';\n"
"    const HELMET_GLB_CDN =\n"
"      'https://static.poly.pizza/535cb2d4-eb2a-441d-899b-d0a5ebd3e37d.glb';\n"
"    const HELMET_GLB = servedFromEsp ? HELMET_GLB_CDN : HELMET_GLB_LOCAL;\n"
"    const HELMET_ROT_X = 0;\n"
"    const HELMET_ROT_Y = 0;\n"
"    const HELMET_ROT_Z = 0;\n"
"\n"
"    const scene = new THREE.Scene();\n"
"    scene.background = new THREE.Color(0x1a1a2e);\n"
"\n"
"    const camera = new THREE.PerspectiveCamera(50, innerWidth / innerHeight, 0.1, 100);\n"
"    camera.position.set(2.5, 2, 2.5);\n"
"\n"
"    const renderer = new THREE.WebGLRenderer({ antialias: true });\n"
"    renderer.setSize(innerWidth, innerHeight);\n"
"    renderer.setPixelRatio(devicePixelRatio);\n"
"    renderer.outputColorSpace = THREE.SRGBColorSpace;\n"
"    renderer.toneMapping = THREE.ACESFilmicToneMapping;\n"
"    document.body.appendChild(renderer.domElement);\n"
"\n"
"    const controls = new OrbitControls(camera, renderer.domElement);\n"
"    controls.enableDamping = true;\n"
"\n"
"    scene.add(new THREE.AmbientLight(0xffffff, 0.55));\n"
"    const dir = new THREE.DirectionalLight(0xffffff, 1.1);\n"
"    dir.position.set(3, 5, 2);\n"
"    scene.add(dir);\n"
"    const fill = new THREE.DirectionalLight(0xaaccff, 0.35);\n"
"    fill.position.set(-2, 1, -3);\n"
"    scene.add(fill);\n"
"\n"
"    const avatar = new THREE.Group();\n"
"    scene.add(avatar);\n"
"\n"
"    const helmetPivot = new THREE.Group();\n"
"    avatar.add(helmetPivot);\n"
"    avatar.add(new THREE.AxesHelper(1.2));\n"
"\n"
"    const displayQuat = new THREE.Quaternion();\n"
"    const STILL_QUAT_EPS = 0.0008;\n"
"    const STEP_DISTANCE = 0.5;\n"
"    const GYRO_DEADBAND_DPS = 2.0;\n"
"    const stepDir = new THREE.Vector3();\n"
"\n"
"    let helmetScene = null;\n"
"    const helmetTint = { still: 0xf5f5f5, walk: 0xd8f5dc };\n"
"\n"
"    function buildSafetyHelmet() {\n"
"      const helmet = new THREE.Group();\n"
"      const shell = new THREE.MeshStandardMaterial({\n"
"        color: helmetTint.still,\n"
"        roughness: 0.42,\n"
"        metalness: 0.06,\n"
"      });\n"
"\n"
"      const profile = [\n"
"        new THREE.Vector2(0.0, 0.52),\n"
"        new THREE.Vector2(0.22, 0.5),\n"
"        new THREE.Vector2(0.34, 0.38),\n"
"        new THREE.Vector2(0.38, 0.22),\n"
"        new THREE.Vector2(0.4, 0.1),\n"
"        new THREE.Vector2(0.62, 0.05),\n"
"        new THREE.Vector2(0.72, 0.02),\n"
"        new THREE.Vector2(0.74, 0.0),\n"
"      ];\n"
"      const body = new THREE.Mesh(\n"
"        new THREE.LatheGeometry(profile, 40),\n"
"        shell\n"
"      );\n"
"      body.position.y = -0.02;\n"
"      helmet.add(body);\n"
"\n"
"      const brim = new THREE.Mesh(\n"
"        new THREE.TorusGeometry(0.7, 0.045, 12, 40),\n"
"        shell\n"
"      );\n"
"      brim.rotation.x = Math.PI / 2;\n"
"      brim.position.y = 0.02;\n"
"      helmet.add(brim);\n"
"\n"
"      const peak = new THREE.Mesh(\n"
"        new THREE.BoxGeometry(0.06, 0.04, 0.22),\n"
"        shell\n"
"      );\n"
"      peak.position.set(0, 0.34, 0.38);\n"
"      helmet.add(peak);\n"
"\n"
"      const button = new THREE.Mesh(\n"
"        new THREE.CylinderGeometry(0.04, 0.04, 0.03, 12),\n"
"        shell\n"
"      );\n"
"      button.position.set(0, 0.5, 0);\n"
"      helmet.add(button);\n"
"\n"
"      helmet.scale.setScalar(1.2);\n"
"      return helmet;\n"
"    }\n"
"\n"
"    function normalizeHelmetModel(root) {\n"
"      const box = new THREE.Box3().setFromObject(root);\n"
"      const size = box.getSize(new THREE.Vector3());\n"
"      const center = box.getCenter(new THREE.Vector3());\n"
"      const maxDim = Math.max(size.x, size.y, size.z, 0.001);\n"
"      const scale = 1.1 / maxDim;\n"
"      root.position.sub(center);\n"
"      root.position.multiplyScalar(scale);\n"
"      root.scale.setScalar(scale);\n"
"      root.rotation.set(HELMET_ROT_X, HELMET_ROT_Y, HELMET_ROT_Z);\n"
"      root.traverse((obj) => {\n"
"        if (!obj.isMesh || !obj.material) return;\n"
"        const mats = Array.isArray(obj.material) ? obj.material : [obj.material];\n"
"        for (const mat of mats) {\n"
"          if (mat.color) mat.color.setHex(helmetTint.still);\n"
"          if (mat.metalness !== undefined) mat.metalness = Math.min(mat.metalness, 0.15);\n"
"        }\n"
"      });\n"
"    }\n"
"\n"
"    function loadHelmetGlb(url) {\n"
"      return new Promise((resolve, reject) => {\n"
"        new GLTFLoader().load(\n"
"          url,\n"
"          (gltf) => {\n"
"            normalizeHelmetModel(gltf.scene);\n"
"            resolve(gltf.scene);\n"
"          },\n"
"          undefined,\n"
"          reject\n"
"        );\n"
"      });\n"
"    }\n"
"\n"
"    function setHelmetTint(hex) {\n"
"      if (!helmetScene) return;\n"
"      helmetScene.traverse((obj) => {\n"
"        if (!obj.isMesh || !obj.material) return;\n"
"        const mats = Array.isArray(obj.material) ? obj.material : [obj.material];\n"
"        for (const mat of mats) {\n"
"          if (mat.color) mat.color.setHex(hex);\n"
"        }\n"
"      });\n"
"    }\n"
"\n"
"    function applyOrientation(q, lockStill) {\n"
"      const incoming = new THREE.Quaternion(q.x, q.y, q.z, q.w);\n"
"      if (lockStill) {\n"
"        return;\n"
"      }\n"
"      if (displayQuat.dot(incoming) < 0) {\n"
"        incoming.x = -incoming.x;\n"
"        incoming.y = -incoming.y;\n"
"        incoming.z = -incoming.z;\n"
"        incoming.w = -incoming.w;\n"
"      }\n"
"      const dot = Math.abs(displayQuat.dot(incoming));\n"
"      if (dot > 1 - STILL_QUAT_EPS) {\n"
"        return;\n"
"      }\n"
"      displayQuat.copy(incoming);\n"
"      helmetPivot.quaternion.copy(displayQuat);\n"
"    }\n"
"\n"
"    async function initHelmet() {\n"
"      const urls = [HELMET_GLB, HELMET_GLB_CDN, HELMET_GLB_LOCAL].filter(\n"
"        (u, i, a) => u && a.indexOf(u) === i\n"
"      );\n"
"      for (const url of urls) {\n"
"        try {\n"
"          helmetScene = await loadHelmetGlb(url);\n"
"          helmetPivot.add(helmetScene);\n"
"          return;\n"
"        } catch (e) {\n"
"          console.warn('helmet load failed:', url, e);\n"
"        }\n"
"      }\n"
"      helmetScene = buildSafetyHelmet();\n"
"      helmetPivot.add(helmetScene);\n"
"    }\n"
"    initHelmet();\n"
"\n"
"    let ws;\n"
"    let frameCount = 0;\n"
"    let lastFpsTime = performance.now();\n"
"    let lastQuat = { w: 1, x: 0, y: 0, z: 0 };\n"
"    let lastQuatChange = 0;\n"
"    let lastMsgTime = 0;\n"
"    let lastHeadingTs = 0;\n"
"    let lastWalking = false;\n"
"    let lastWalkingTime = 0;\n"
"    let heading = 0;\n"
"    let lastSteps = 0;\n"
"\n"
"    function quatYawRad() {\n"
"      const e = new THREE.Euler(0, 0, 0, 'YXZ');\n"
"      e.setFromQuaternion(helmetPivot.quaternion);\n"
"      return e.y;\n"
"    }\n"
"\n"
"    function resetAvatarPose() {\n"
"      avatar.position.set(0, 0, 0);\n"
"      heading = 0;\n"
"      lastSteps = 0;\n"
"      lastHeadingTs = 0;\n"
"      displayQuat.set(0, 0, 0, 1);\n"
"      helmetPivot.quaternion.set(0, 0, 0, 1);\n"
"    }\n"
"\n"
"    function updateHeading(gzDps, nowMs, snapFromQuat) {\n"
"      if (snapFromQuat) {\n"
"        heading = quatYawRad();\n"
"        lastHeadingTs = nowMs;\n"
"        return;\n"
"      }\n"
"      if (lastHeadingTs > 0) {\n"
"        const dt = Math.min((nowMs - lastHeadingTs) / 1000, 0.08);\n"
"        const gz = Math.abs(gzDps) < GYRO_DEADBAND_DPS ? 0 : gzDps;\n"
"        heading += (gz * Math.PI / 180) * dt;\n"
"      }\n"
"      lastHeadingTs = nowMs;\n"
"    }\n"
"\n"
"    function advanceWalk(stepsDelta) {\n"
"      if (stepsDelta <= 0) return;\n"
"      stepDir.set(Math.sin(heading), 0, -Math.cos(heading));\n"
"      avatar.position.addScaledVector(stepDir, STEP_DISTANCE * stepsDelta);\n"
"    }\n"
"\n"
"    function setStatus(text, ok) {\n"
"      statusEl.textContent = text;\n"
"      statusEl.className = ok ? 'ok' : 'err';\n"
"    }\n"
"\n"
"    function setVital(el, text, ok) {\n"
"      el.textContent = text;\n"
"      el.classList.toggle('missing', !ok);\n"
"    }\n"
"\n"
"    function updateVitals(q) {\n"
"      if (typeof q.temp === 'number' && !Number.isNaN(q.temp)) {\n"
"        setVital(vTempEl, `${q.temp.toFixed(1)} °C`, true);\n"
"      } else {\n"
"        setVital(vTempEl, '--', false);\n"
"      }\n"
"      if (typeof q.hr === 'number' && q.hr > 0) {\n"
"        setVital(vHrEl, `${q.hr} bpm`, true);\n"
"      } else {\n"
"        setVital(vHrEl, '--', false);\n"
"      }\n"
"      if (typeof q.spo2 === 'number' && q.spo2 > 0) {\n"
"        setVital(vSpo2El, `${q.spo2}%`, true);\n"
"      } else {\n"
"        setVital(vSpo2El, '--', false);\n"
"      }\n"
"      if (typeof q.mq135 === 'number' && q.mq135 >= 0) {\n"
"        setVital(vMq135El, `${q.mq135}`, true);\n"
"      } else {\n"
"        setVital(vMq135El, '--', false);\n"
"      }\n"
"      if (typeof q.mq136 === 'number' && q.mq136 >= 0) {\n"
"        setVital(vMq136El, `${q.mq136}`, true);\n"
"      } else {\n"
"        setVital(vMq136El, '--', false);\n"
"      }\n"
"      if (typeof q.mq4 === 'number' && q.mq4 >= 0) {\n"
"        setVital(vMq4El, `${q.mq4}`, true);\n"
"      } else {\n"
"        setVital(vMq4El, '--', false);\n"
"      }\n"
"      if (typeof q.mq7 === 'number' && q.mq7 >= 0) {\n"
"        setVital(vMq7El, `${q.mq7}`, true);\n"
"      } else {\n"
"        setVital(vMq7El, '--', false);\n"
"      }\n"
"    }\n"
"\n"
"    function setActivity(walking, steps) {\n"
"      if (walking) {\n"
"        activityEl.textContent = `Walking · ${steps} steps`;\n"
"        activityEl.className = 'walking';\n"
"        setHelmetTint(helmetTint.walk);\n"
"      } else {\n"
"        activityEl.textContent = steps > 0 ? `Still · ${steps} steps` : 'Still';\n"
"        activityEl.className = 'still';\n"
"        setHelmetTint(helmetTint.still);\n"
"      }\n"
"    }\n"
"\n"
"    function quatChanged(q) {\n"
"      const e = 0.0005;\n"
"      return Math.abs(q.w - lastQuat.w) > e || Math.abs(q.x - lastQuat.x) > e ||\n"
"             Math.abs(q.y - lastQuat.y) > e || Math.abs(q.z - lastQuat.z) > e;\n"
"    }\n"
"\n"
"    function wsUrl() {\n"
"      const q = new URLSearchParams(location.search).get('ip');\n"
"      if (q) {\n"
"        return `ws://${q}/ws`;\n"
"      }\n"
"      if (servedFromEsp && location.host) {\n"
"        const proto = location.protocol === 'https:' ? 'wss:' : 'ws:';\n"
"        return `${proto}//${location.host}/ws`;\n"
"      }\n"
"      const ip = (espIpInput.value || localStorage.getItem('espIp') || '').trim();\n"
"      if (!ip) {\n"
"        return null;\n"
"      }\n"
"      localStorage.setItem('espIp', ip);\n"
"      return `ws://${ip}/ws`;\n"
"    }\n"
"\n"
"    function connect() {\n"
"      if (ws) {\n"
"        ws.onclose = null;\n"
"        ws.close();\n"
"        ws = null;\n"
"      }\n"
"\n"
"      const url = wsUrl();\n"
"      if (!url) {\n"
"        setStatus('Enter ESP32 IP below (from serial monitor)', false);\n"
"        return;\n"
"      }\n"
"\n"
"      if (!servedFromEsp) {\n"
"        setStatus(`Connecting to ${url}…`, true);\n"
"      }\n"
"\n"
"      ws = new WebSocket(url);\n"
"\n"
"      ws.onopen = () => {\n"
"        lastMsgTime = 0;\n"
"        lastQuatChange = 0;\n"
"        lastWalking = false;\n"
"        lastWalkingTime = 0;\n"
"        resetAvatarPose();\n"
"        setActivity(false, 0);\n"
"        updateVitals({});\n"
"        setStatus('Connected — waiting for data…', true);\n"
"        ws.send('hello');\n"
"      };\n"
"      ws.onclose = () => {\n"
"        setStatus('Disconnected — retrying…', false);\n"
"        setTimeout(connect, 2000);\n"
"      };\n"
"      ws.onerror = () => setStatus(`WebSocket failed (${url})`, false);\n"
"      ws.onmessage = (ev) => {\n"
"        try {\n"
"          const q = JSON.parse(ev.data);\n"
"          const now = performance.now();\n"
"          const walking = !!q.walking;\n"
"          const imuStill = q.still === true;\n"
"          const calibrated = q.calibrated === true;\n"
"          const steps = q.steps || 0;\n"
"          const gz = typeof q.gz === 'number' ? q.gz : 0;\n"
"\n"
"          if (!calibrated) {\n"
"            setStatus('Hold helmet still to calibrate…', true);\n"
"          }\n"
"\n"
"          applyOrientation(q, imuStill && !walking && calibrated);\n"
"          setActivity(walking, steps);\n"
"          updateVitals(q);\n"
"          const quatSnap = quatChanged(q);\n"
"          updateHeading(gz, now, quatSnap);\n"
"          if (quatSnap) {\n"
"            lastQuat = q;\n"
"            lastQuatChange = now;\n"
"          }\n"
"          if (steps < lastSteps) {\n"
"            resetAvatarPose();\n"
"          }\n"
"          if (steps > lastSteps) {\n"
"            if (walking) {\n"
"              advanceWalk(steps - lastSteps);\n"
"            }\n"
"            lastSteps = steps;\n"
"          }\n"
"          frameCount++;\n"
"          lastMsgTime = now;\n"
"          if (walking !== lastWalking) {\n"
"            lastWalking = walking;\n"
"            lastWalkingTime = now;\n"
"          }\n"
"          if (!calibrated) {\n"
"            /* status set above */\n"
"          } else if (walking) {\n"
"            setStatus('Live IMU data', true);\n"
"          } else if (lastQuatChange > 0) {\n"
"            setStatus('Streaming OK — device still', true);\n"
"          } else if (ws.readyState === WebSocket.OPEN) {\n"
"            setStatus('Connected — calibrated', true);\n"
"          }\n"
"        } catch (_) {}\n"
"      };\n"
"    }\n"
"\n"
"    resetBtn.onclick = () => {\n"
"      resetAvatarPose();\n"
"      if (ws && ws.readyState === WebSocket.OPEN) {\n"
"        ws.send('reset');\n"
"      }\n"
"    };\n"
"\n"
"    if (!servedFromEsp) {\n"
"      ipRow.hidden = false;\n"
"      espIpInput.value = localStorage.getItem('espIp') || '';\n"
"      setStatus('Open http://ESP_IP/ from serial — or enter IP here', false);\n"
"      connectBtn.onclick = () => connect();\n"
"    } else {\n"
"      connect();\n"
"    }\n"
"\n"
"    function animate() {\n"
"      requestAnimationFrame(animate);\n"
"      controls.update();\n"
"      renderer.render(scene, camera);\n"
"\n"
"      const now = performance.now();\n"
"      if (now - lastFpsTime >= 1000) {\n"
"        fpsEl.textContent = `FPS: ${frameCount}`;\n"
"        frameCount = 0;\n"
"        lastFpsTime = now;\n"
"        if (ws && ws.readyState === WebSocket.OPEN) {\n"
"          if (lastMsgTime === 0) {\n"
"            const hint = servedFromEsp\n"
"              ? 'Connected — no data from ESP (reflash firmware)'\n"
"              : 'Connected — no data. Open http://ESP_IP/ in the browser';\n"
"            setStatus(hint, false);\n"
"          } else if (lastWalking && now - lastWalkingTime < 3000) {\n"
"            setStatus('Live IMU data', true);\n"
"          } else if (now - lastQuatChange > 2000) {\n"
"            setStatus('Streaming OK — device still', true);\n"
"          } else if (lastQuatChange > 0) {\n"
"            setStatus('Live IMU data', true);\n"
"          }\n"
"        }\n"
"      }\n"
"    }\n"
"    animate();\n"
"\n"
"    addEventListener('resize', () => {\n"
"      camera.aspect = innerWidth / innerHeight;\n"
"      camera.updateProjectionMatrix();\n"
"      renderer.setSize(innerWidth, innerHeight);\n"
"    });\n"
"  </script>\n"
"</body>\n"
"</html>\n"
;

const size_t index_html_len = sizeof(index_html) - 1;
