#include "index_html.h"

const char index_html[] =
"<!DOCTYPE html>\n"
"<html lang=\"en\">\n"
"<head>\n"
"  <meta charset=\"UTF-8\" />\n"
"  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />\n"
"  <title>IMU 3D Viewer</title>\n"
"  <style>\n"
"    * { margin: 0; padding: 0; box-sizing: border-box; }\n"
"    body { overflow: hidden; background: #1a1a2e; font-family: system-ui, sans-serif; }\n"
"    #hud {\n"
"      position: fixed; top: 12px; left: 12px; z-index: 10;\n"
"      color: #eee; background: rgba(0,0,0,0.55); padding: 10px 14px;\n"
"      border-radius: 8px; font-size: 14px; line-height: 1.5;\n"
"    }\n"
"    #hud button {\n"
"      margin-top: 8px; padding: 6px 14px; cursor: pointer;\n"
"      border: none; border-radius: 6px; background: #4a9eff; color: #fff;\n"
"      font-size: 14px;\n"
"    }\n"
"    #hud button:hover { background: #3a8eef; }\n"
"    #ipRow { margin-top: 8px; display: flex; gap: 6px; align-items: center; }\n"
"    #ipRow input {\n"
"      width: 130px; padding: 4px 8px; border-radius: 4px; border: none;\n"
"      font-size: 13px;\n"
"    }\n"
"    .ok { color: #6f6; }\n"
"    .err { color: #f66; }\n"
"    #activity {\n"
"      margin-top: 6px; padding: 6px 10px; border-radius: 6px;\n"
"      font-weight: 600; letter-spacing: 0.02em;\n"
"    }\n"
"    #activity.still { background: rgba(255,255,255,0.08); color: #bbb; }\n"
"    #activity.walking { background: rgba(80,200,120,0.25); color: #8f8; }\n"
"  </style>\n"
"</head>\n"
"<body>\n"
"  <div id=\"hud\">\n"
"    <div id=\"status\">Connecting…</div>\n"
"    <div id=\"fps\">FPS: —</div>\n"
"    <div id=\"activity\" class=\"still\">Still</div>\n"
"    <div id=\"ipRow\" hidden>\n"
"      <input id=\"espIp\" type=\"text\" placeholder=\"192.168.0.195\" />\n"
"      <button id=\"connectBtn\" type=\"button\">Connect</button>\n"
"    </div>\n"
"    <button id=\"resetBtn\" type=\"button\">Reset orientation</button>\n"
"  </div>\n"
"  <script type=\"importmap\">\n"
"  {\n"
"    \"imports\": {\n"
"      \"three\": \"https://cdn.jsdelivr.net/npm/three@0.160.0/build/three.module.js\",\n"
"      \"three/addons/\": \"https://cdn.jsdelivr.net/npm/three@0.160.0/examples/jsm/\"\n"
"    }\n"
"  }\n"
"  </script>\n"
"  <script type=\"module\">\n"
"    import * as THREE from 'three';\n"
"    import { OrbitControls } from 'three/addons/controls/OrbitControls.js';\n"
"\n"
"    const statusEl = document.getElementById('status');\n"
"    const fpsEl = document.getElementById('fps');\n"
"    const activityEl = document.getElementById('activity');\n"
"    const resetBtn = document.getElementById('resetBtn');\n"
"    const ipRow = document.getElementById('ipRow');\n"
"    const espIpInput = document.getElementById('espIp');\n"
"    const connectBtn = document.getElementById('connectBtn');\n"
"    const servedFromEsp = location.protocol === 'http:' || location.protocol === 'https:';\n"
"\n"
"    const scene = new THREE.Scene();\n"
"    scene.background = new THREE.Color(0x1a1a2e);\n"
"\n"
"    const camera = new THREE.PerspectiveCamera(50, innerWidth / innerHeight, 0.1, 100);\n"
"    camera.position.set(2.5, 2, 2.5);\n"
"\n"
"    const renderer = new THREE.WebGLRenderer({ antialias: true });\n"
"    renderer.setSize(innerWidth, innerHeight);\n"
"    renderer.setPixelRatio(devicePixelRatio);\n"
"    document.body.appendChild(renderer.domElement);\n"
"\n"
"    const controls = new OrbitControls(camera, renderer.domElement);\n"
"    controls.enableDamping = true;\n"
"\n"
"    scene.add(new THREE.AmbientLight(0xffffff, 0.6));\n"
"    const dir = new THREE.DirectionalLight(0xffffff, 0.9);\n"
"    dir.position.set(3, 5, 2);\n"
"    scene.add(dir);\n"
"\n"
"    const avatar = new THREE.Group();\n"
"    scene.add(avatar);\n"
"\n"
"    const boxMaterial = new THREE.MeshStandardMaterial({\n"
"      color: 0x4a9eff, metalness: 0.2, roughness: 0.5\n"
"    });\n"
"    const box = new THREE.Mesh(new THREE.BoxGeometry(1.2, 0.7, 0.35), boxMaterial);\n"
"    avatar.add(box);\n"
"    avatar.add(new THREE.AxesHelper(1.5));\n"
"\n"
"    const STEP_DISTANCE = 0.5;\n"
"    const GYRO_DEADBAND_DPS = 0.8;\n"
"    const stepDir = new THREE.Vector3();\n"
"\n"
"    let ws;\n"
"    let frameCount = 0;\n"
"    let lastFpsTime = performance.now();\n"
"    let lastQuat = { w: 1, x: 0, y: 0, z: 0 };\n"
"    let lastQuatChange = 0;\n"
"    let lastMsgTime = 0;\n"
"    let lastHeadingTs = 0;\n"
"    let lastWalking = false;\n"
"    let lastWalkingTime = 0;\n"
"    let heading = 0;\n"
"    let lastSteps = 0;\n"
"\n"
"    function quatYawRad() {\n"
"      const e = new THREE.Euler(0, 0, 0, 'YXZ');\n"
"      e.setFromQuaternion(box.quaternion);\n"
"      return e.y;\n"
"    }\n"
"\n"
"    function resetAvatarPose() {\n"
"      avatar.position.set(0, 0, 0);\n"
"      heading = 0;\n"
"      lastSteps = 0;\n"
"      lastHeadingTs = 0;\n"
"    }\n"
"\n"
"    function updateHeading(gzDps, nowMs, snapFromQuat) {\n"
"      if (snapFromQuat) {\n"
"        heading = quatYawRad();\n"
"        lastHeadingTs = nowMs;\n"
"        return;\n"
"      }\n"
"      if (lastHeadingTs > 0) {\n"
"        const dt = Math.min((nowMs - lastHeadingTs) / 1000, 0.08);\n"
"        const gz = Math.abs(gzDps) < GYRO_DEADBAND_DPS ? 0 : gzDps;\n"
"        heading += (gz * Math.PI / 180) * dt;\n"
"      }\n"
"      lastHeadingTs = nowMs;\n"
"    }\n"
"\n"
"    function advanceWalk(stepsDelta) {\n"
"      if (stepsDelta <= 0) return;\n"
"      stepDir.set(Math.sin(heading), 0, -Math.cos(heading));\n"
"      avatar.position.addScaledVector(stepDir, STEP_DISTANCE * stepsDelta);\n"
"    }\n"
"\n"
"    function setStatus(text, ok) {\n"
"      statusEl.textContent = text;\n"
"      statusEl.className = ok ? 'ok' : 'err';\n"
"    }\n"
"\n"
"    function setActivity(walking, steps) {\n"
"      if (walking) {\n"
"        activityEl.textContent = `Walking · ${steps} steps`;\n"
"        activityEl.className = 'walking';\n"
"        boxMaterial.color.setHex(0x5fd68a);\n"
"      } else {\n"
"        activityEl.textContent = steps > 0 ? `Still · ${steps} steps` : 'Still';\n"
"        activityEl.className = 'still';\n"
"        boxMaterial.color.setHex(0x4a9eff);\n"
"      }\n"
"    }\n"
"\n"
"    function quatChanged(q) {\n"
"      const e = 0.0005;\n"
"      return Math.abs(q.w - lastQuat.w) > e || Math.abs(q.x - lastQuat.x) > e ||\n"
"             Math.abs(q.y - lastQuat.y) > e || Math.abs(q.z - lastQuat.z) > e;\n"
"    }\n"
"\n"
"    function wsUrl() {\n"
"      const q = new URLSearchParams(location.search).get('ip');\n"
"      if (q) {\n"
"        return `ws://${q}/ws`;\n"
"      }\n"
"      if (servedFromEsp && location.host) {\n"
"        const proto = location.protocol === 'https:' ? 'wss:' : 'ws:';\n"
"        return `${proto}//${location.host}/ws`;\n"
"      }\n"
"      const ip = (espIpInput.value || localStorage.getItem('espIp') || '').trim();\n"
"      if (!ip) {\n"
"        return null;\n"
"      }\n"
"      localStorage.setItem('espIp', ip);\n"
"      return `ws://${ip}/ws`;\n"
"    }\n"
"\n"
"    function connect() {\n"
"      if (ws) {\n"
"        ws.onclose = null;\n"
"        ws.close();\n"
"        ws = null;\n"
"      }\n"
"\n"
"      const url = wsUrl();\n"
"      if (!url) {\n"
"        setStatus('Enter ESP32 IP below (from serial monitor)', false);\n"
"        return;\n"
"      }\n"
"\n"
"      if (!servedFromEsp) {\n"
"        setStatus(`Connecting to ${url}…`, true);\n"
"      }\n"
"\n"
"      ws = new WebSocket(url);\n"
"\n"
"      ws.onopen = () => {\n"
"        lastMsgTime = 0;\n"
"        lastQuatChange = 0;\n"
"        lastWalking = false;\n"
"        lastWalkingTime = 0;\n"
"        resetAvatarPose();\n"
"        setActivity(false, 0);\n"
"        setStatus('Connected — waiting for data…', true);\n"
"        ws.send('hello');\n"
"      };\n"
"      ws.onclose = () => {\n"
"        setStatus('Disconnected — retrying…', false);\n"
"        setTimeout(connect, 2000);\n"
"      };\n"
"      ws.onerror = () => setStatus(`WebSocket failed (${url})`, false);\n"
"      ws.onmessage = (ev) => {\n"
"        try {\n"
"          const q = JSON.parse(ev.data);\n"
"          const now = performance.now();\n"
"          const walking = !!q.walking;\n"
"          const steps = q.steps || 0;\n"
"          const gz = typeof q.gz === 'number' ? q.gz : 0;\n"
"          box.quaternion.set(q.x, q.y, q.z, q.w);\n"
"          setActivity(walking, steps);\n"
"          const quatSnap = quatChanged(q);\n"
"          updateHeading(gz, now, quatSnap);\n"
"          if (quatSnap) {\n"
"            lastQuat = q;\n"
"            lastQuatChange = now;\n"
"          }\n"
"          if (steps < lastSteps) {\n"
"            resetAvatarPose();\n"
"          }\n"
"          if (steps > lastSteps) {\n"
"            if (walking) {\n"
"              advanceWalk(steps - lastSteps);\n"
"            }\n"
"            lastSteps = steps;\n"
"          }\n"
"          frameCount++;\n"
"          lastMsgTime = now;\n"
"          if (walking !== lastWalking) {\n"
"            lastWalking = walking;\n"
"            lastWalkingTime = now;\n"
"          }\n"
"          if (walking) {\n"
"            setStatus('Live IMU data', true);\n"
"          } else if (lastQuatChange > 0) {\n"
"            setStatus('Live IMU data', true);\n"
"          }\n"
"        } catch (_) {}\n"
"      };\n"
"    }\n"
"\n"
"    resetBtn.onclick = () => {\n"
"      resetAvatarPose();\n"
"      if (ws && ws.readyState === WebSocket.OPEN) {\n"
"        ws.send('reset');\n"
"      }\n"
"    };\n"
"\n"
"    if (!servedFromEsp) {\n"
"      ipRow.hidden = false;\n"
"      espIpInput.value = localStorage.getItem('espIp') || '';\n"
"      setStatus('Open http://ESP_IP/ from serial — or enter IP here', false);\n"
"      connectBtn.onclick = () => connect();\n"
"    } else {\n"
"      connect();\n"
"    }\n"
"\n"
"    function animate() {\n"
"      requestAnimationFrame(animate);\n"
"      controls.update();\n"
"      renderer.render(scene, camera);\n"
"\n"
"      const now = performance.now();\n"
"      if (now - lastFpsTime >= 1000) {\n"
"        fpsEl.textContent = `FPS: ${frameCount}`;\n"
"        frameCount = 0;\n"
"        lastFpsTime = now;\n"
"        if (ws && ws.readyState === WebSocket.OPEN) {\n"
"          if (lastMsgTime === 0) {\n"
"            const hint = servedFromEsp\n"
"              ? 'Connected — no data from ESP (reflash firmware)'\n"
"              : 'Connected — no data. Open http://ESP_IP/ in the browser';\n"
"            setStatus(hint, false);\n"
"          } else if (lastWalking && now - lastWalkingTime < 3000) {\n"
"            setStatus('Live IMU data', true);\n"
"          } else if (now - lastQuatChange > 2000) {\n"
"            setStatus('Streaming OK — device still', true);\n"
"          } else if (lastQuatChange > 0) {\n"
"            setStatus('Live IMU data', true);\n"
"          }\n"
"        }\n"
"      }\n"
"    }\n"
"    animate();\n"
"\n"
"    addEventListener('resize', () => {\n"
"      camera.aspect = innerWidth / innerHeight;\n"
"      camera.updateProjectionMatrix();\n"
"      renderer.setSize(innerWidth, innerHeight);\n"
"    });\n"
"  </script>\n"
"</body>\n"
"</html>\n"
;

const size_t index_html_len = 9861;
